/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/macroResults`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/nutritionGoal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/personalInformation`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/school`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/tdeeCalculator`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcomeFirst`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/macroResults`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/nutritionGoal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/personalInformation`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/school`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/tdeeCalculator`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcomeFirst`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diary${`?${string}` | `#${string}` | ''}` | `/diary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/plan${`?${string}` | `#${string}` | ''}` | `/plan${`?${string}` | `#${string}` | ''}` | `/onboarding/macroResults${`?${string}` | `#${string}` | ''}` | `/onboarding/nutritionGoal${`?${string}` | `#${string}` | ''}` | `/onboarding/personalInformation${`?${string}` | `#${string}` | ''}` | `/onboarding/preferences${`?${string}` | `#${string}` | ''}` | `/onboarding/ready${`?${string}` | `#${string}` | ''}` | `/onboarding/school${`?${string}` | `#${string}` | ''}` | `/onboarding/tdeeCalculator${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | `/onboarding/welcomeFirst${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/macroResults`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/nutritionGoal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/personalInformation`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/school`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/tdeeCalculator`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcomeFirst`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
